"""
Export utilities for the ESG Signal briefing.

Provides two export formats:
  - PDF via ReportLab (reportlab==4.2.2, installed in requirements-ui.txt)
  - Structured JSON for programmatic consumption

Public API
----------
    pdf_bytes = to_pdf(report, profile, dcf_result=None)
    json_str  = to_json(report, profile, dcf_result=None)

Both functions return bytes / str ready to be passed to st.download_button.
They never raise — on error they return a minimal fallback and log the issue.
"""

import dataclasses
import json
import logging
from io import BytesIO

LOGGER = logging.getLogger(__name__)

# ReportLab is in requirements-ui.txt, not requirements.txt.  Guard the import
# so that pytest (which uses requirements.txt) can still import this module.
try:
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
    from reportlab.lib.units import cm
    from reportlab.platypus import (
        HRFlowable,
        Paragraph,
        SimpleDocTemplate,
        Spacer,
        Table,
        TableStyle,
    )

    _REPORTLAB_AVAILABLE = True
except ImportError:  # pragma: no cover
    _REPORTLAB_AVAILABLE = False


# ---------------------------------------------------------------------------
# Colour map
# ---------------------------------------------------------------------------

_FLAG_RGB = {
    "green": colors.HexColor("#28a745") if _REPORTLAB_AVAILABLE else None,
    "amber": colors.HexColor("#ffc107") if _REPORTLAB_AVAILABLE else None,
    "red": colors.HexColor("#dc3545") if _REPORTLAB_AVAILABLE else None,
}
_GREY = colors.HexColor("#6c757d") if _REPORTLAB_AVAILABLE else None

_STREAM_LABELS = {
    "disclosure": "Disclosure Quality (30%)",
    "regulatory": "Regulatory Record (25%)",
    "talent": "Talent Signal (20%)",
    "words_money": "Words vs Money (15%)",
    "supply_chain": "Supply Chain (10%)",
}

_FOOTER = (
    "Generated by ESG Signal — HAL 9000 Team, University of East Anglia. For research use only."
)


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def to_pdf(report, profile=None, dcf_result=None) -> bytes:
    """
    Generate a PDF briefing document for one company.

    Args:
        report:     CredibilityReport from the pipeline.
        profile:    Optional CompanyProfile (used for country / filing date).
        dcf_result: Optional DcfMapperResult.

    Returns:
        Raw PDF bytes, or a minimal error PDF if ReportLab is unavailable.
    """
    if not _REPORTLAB_AVAILABLE:
        LOGGER.warning("to_pdf: reportlab not installed — returning empty PDF placeholder")
        return b"%PDF-1.4\n% ReportLab not installed\n"

    try:
        return _build_pdf(report, profile, dcf_result)
    except Exception as exc:
        LOGGER.exception("to_pdf failed: %s", exc)
        return b"%PDF-1.4\n% Export error\n"


def to_json(report, profile=None, dcf_result=None) -> str:
    """
    Serialise the pipeline output to a structured JSON string.

    The JSON contains three top-level keys:
      - "credibility_report": full CredibilityReport as a dict
      - "company_profile": CompanyProfile dict (None if not provided)
      - "dcf_result": DcfMapperResult dict (None if not provided)

    Returns:
        UTF-8 JSON string.
    """
    try:
        payload = {
            "credibility_report": dataclasses.asdict(report),
            "company_profile": dataclasses.asdict(profile) if profile else None,
            "dcf_result": dataclasses.asdict(dcf_result) if dcf_result else None,
        }
        return json.dumps(payload, indent=2, default=str)
    except Exception as exc:
        LOGGER.exception("to_json failed: %s", exc)
        return json.dumps({"error": str(exc)})


# ---------------------------------------------------------------------------
# PDF builder (internal)
# ---------------------------------------------------------------------------


def _build_pdf(report, profile, dcf_result) -> bytes:
    buf = BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=A4,
        leftMargin=2 * cm,
        rightMargin=2 * cm,
        topMargin=2 * cm,
        bottomMargin=2 * cm,
    )

    styles = getSampleStyleSheet()
    style_h1 = ParagraphStyle("H1", parent=styles["Heading1"], fontSize=18, spaceAfter=6)
    style_h2 = ParagraphStyle("H2", parent=styles["Heading2"], fontSize=13, spaceAfter=4)
    style_body = ParagraphStyle(
        "Body", parent=styles["Normal"], fontSize=9, spaceAfter=4, leading=13
    )
    style_caption = ParagraphStyle(
        "Caption", parent=styles["Normal"], fontSize=8, textColor=_GREY, leading=11
    )
    style_footer = ParagraphStyle(
        "Footer", parent=styles["Normal"], fontSize=7, textColor=_GREY, alignment=1
    )

    story = []

    # ------------------------------------------------------------------
    # Header
    # ------------------------------------------------------------------
    story.append(Paragraph(f"ESG Signal Briefing — {report.company_name}", style_h1))
    meta_parts = [f"Ticker: {report.ticker or '—'}"]
    if report.sasb_industry:
        meta_parts.append(f"SASB Industry: {report.sasb_industry}")
    if profile and profile.country:
        meta_parts.append(f"Country: {profile.country}")
    if profile and profile.latest_annual_filing:
        meta_parts.append(f"Filing: {profile.latest_annual_filing.filed_date}")
    story.append(Paragraph("  |  ".join(meta_parts), style_caption))
    story.append(Spacer(1, 0.3 * cm))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#dee2e6")))
    story.append(Spacer(1, 0.3 * cm))

    # ------------------------------------------------------------------
    # Overall score
    # ------------------------------------------------------------------
    flag_colour = _FLAG_RGB.get(report.overall_flag, _GREY)
    story.append(Paragraph("Overall Credibility", style_h2))
    overall_data = [
        ["Score", "Flag"],
        [f"{report.overall_score:.2f}", report.overall_flag.upper()],
    ]
    tbl = Table(overall_data, colWidths=[4 * cm, 4 * cm])
    tbl.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#f8f9fa")),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, -1), 9),
                ("ALIGN", (0, 0), (-1, -1), "CENTER"),
                ("BACKGROUND", (1, 1), (1, 1), flag_colour),
                ("TEXTCOLOR", (1, 1), (1, 1), colors.white),
                ("FONTNAME", (1, 1), (1, 1), "Helvetica-Bold"),
                ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#dee2e6")),
                ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#dee2e6")),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white]),
                ("TOPPADDING", (0, 0), (-1, -1), 5),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
            ]
        )
    )
    story.append(tbl)
    story.append(Spacer(1, 0.4 * cm))

    # ------------------------------------------------------------------
    # Per-factor table
    # ------------------------------------------------------------------
    story.append(Paragraph("Factor Scores", style_h2))
    headers = ["Factor", "Score", "Flag", "Disclosure", "Regulatory", "Talent", "W/M", "Supply"]
    rows = [headers]
    for fs in report.factor_scores:
        ss = fs.stream_scores
        rows.append(
            [
                fs.factor_name,
                f"{fs.score:.2f}",
                fs.flag.upper(),
                f"{ss.get('disclosure', 0):.2f}" if "disclosure" in ss else "—",
                f"{ss.get('regulatory', 0):.2f}" if "regulatory" in ss else "—",
                f"{ss.get('talent', 0):.2f}" if "talent" in ss else "—",
                f"{ss.get('words_money', 0):.2f}" if "words_money" in ss else "—",
                f"{ss.get('supply_chain', 0):.2f}" if "supply_chain" in ss else "—",
            ]
        )

    col_widths = [4.5 * cm, 1.5 * cm, 1.5 * cm, 2 * cm, 2 * cm, 1.8 * cm, 1.4 * cm, 1.8 * cm]
    factor_tbl = Table(rows, colWidths=col_widths)
    flag_row_styles = []
    for row_idx, fs in enumerate(report.factor_scores, start=1):
        fc = _FLAG_RGB.get(fs.flag, _GREY)
        flag_row_styles.append(("BACKGROUND", (2, row_idx), (2, row_idx), fc))
        flag_row_styles.append(("TEXTCOLOR", (2, row_idx), (2, row_idx), colors.white))

    factor_tbl.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#f8f9fa")),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, -1), 8),
                ("ALIGN", (1, 0), (-1, -1), "CENTER"),
                ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#dee2e6")),
                ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#dee2e6")),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f8f9fa")]),
                ("TOPPADDING", (0, 0), (-1, -1), 4),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ]
            + flag_row_styles
        )
    )
    story.append(factor_tbl)
    story.append(Spacer(1, 0.5 * cm))

    # ------------------------------------------------------------------
    # Per-factor narrative
    # ------------------------------------------------------------------
    story.append(Paragraph("Factor Narratives", style_h2))
    for fs in report.factor_scores:
        if not fs.narrative:
            continue
        fc = _FLAG_RGB.get(fs.flag, _GREY)
        story.append(
            Paragraph(
                f'<font color="#{_hex_from_colour(fc)}">'
                f"<b>{fs.factor_name}</b>"
                f" ({fs.flag.upper()}, {fs.score:.2f})</font>",
                style_body,
            )
        )
        story.append(Paragraph(fs.narrative, style_body))
        if fs.evidence:
            for note in fs.evidence:
                story.append(Paragraph(f"• {note}", style_caption))
        story.append(Spacer(1, 0.2 * cm))

    # ------------------------------------------------------------------
    # DCF scenario ranges
    # ------------------------------------------------------------------
    if dcf_result and dcf_result.mappings:
        story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#dee2e6")))
        story.append(Spacer(1, 0.3 * cm))
        story.append(Paragraph("DCF Scenario Impact Ranges", style_h2))
        dcf_headers = ["Factor", "Flag", "Low", "Mid", "High", "Currency", "Source"]
        dcf_rows = [dcf_headers]
        for m in dcf_result.mappings:
            dcf_rows.append(
                [
                    m.factor_name,
                    (m.credibility_flag or "—").upper(),
                    f"{m.scenario_low:,.0f}" if m.scenario_low else "—",
                    f"{m.scenario_mid:,.0f}" if m.scenario_mid else "—",
                    f"{m.scenario_high:,.0f}" if m.scenario_high else "—",
                    m.scenario_currency,
                    m.scenario_source[:40] if m.scenario_source else "—",
                ]
            )
        dcf_tbl = Table(
            dcf_rows,
            colWidths=[3.5 * cm, 1.5 * cm, 2.5 * cm, 2.5 * cm, 2.5 * cm, 1.5 * cm, 3 * cm],
        )
        dcf_flag_styles = []
        for row_idx, m in enumerate(dcf_result.mappings, start=1):
            fc = _FLAG_RGB.get(m.credibility_flag or "amber", _GREY)
            dcf_flag_styles.append(("BACKGROUND", (1, row_idx), (1, row_idx), fc))
            dcf_flag_styles.append(("TEXTCOLOR", (1, row_idx), (1, row_idx), colors.white))
        dcf_tbl.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#f8f9fa")),
                    ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                    ("FONTSIZE", (0, 0), (-1, -1), 8),
                    ("ALIGN", (1, 0), (-1, -1), "CENTER"),
                    ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#dee2e6")),
                    ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#dee2e6")),
                    (
                        "ROWBACKGROUNDS",
                        (0, 1),
                        (-1, -1),
                        [colors.white, colors.HexColor("#f8f9fa")],
                    ),
                    ("TOPPADDING", (0, 0), (-1, -1), 4),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
                ]
                + dcf_flag_styles
            )
        )
        story.append(dcf_tbl)
        story.append(Spacer(1, 0.3 * cm))

    # ------------------------------------------------------------------
    # Validation / error notes
    # ------------------------------------------------------------------
    if report.errors:
        story.append(Paragraph("Validation Notes", style_h2))
        for err in report.errors:
            story.append(Paragraph(f"• {err}", style_caption))
        story.append(Spacer(1, 0.2 * cm))

    # ------------------------------------------------------------------
    # Footer
    # ------------------------------------------------------------------
    story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#dee2e6")))
    story.append(Spacer(1, 0.15 * cm))
    story.append(Paragraph(_FOOTER, style_footer))

    doc.build(story)
    return buf.getvalue()


def _hex_from_colour(colour) -> str:
    """Extract a 6-digit hex string from a ReportLab HexColor for use in XML markup."""
    try:
        return colour.hexval()[1:]  # strip leading #
    except Exception:
        return "6c757d"
